name: Check Dart Formatting

on:
  # Manual Trigger
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head.ref }}
  cancel-in-progress: false

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 'stable'

    - name: dart format
      run: |
        # Run dart format and check for unformatted files
        echo "Running dart format..."
        dart format -o none --set-exit-if-changed .