name: Sample

on:
  # Manual Trigger
  workflow_dispatch:

  push:
    branches:
    - blooby
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head.ref }}
  cancel-in-progress: false

jobs:
  hello_world:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Hello World
      run: |
        echo "hello world"
        echo ${GITHUB_WORKSPACE}

        cd ..
        MY_ROOT=`pwd`
        mkdir -p ${MY_ROOT}/my-flutter
        cp -r ${GITHUB_WORKSPACE} ${MY_ROOT}/my-flutter/
        mv ${MY_ROOT}/my-flutter/sample ${MY_ROOT}/my-flutter/engine
        ls -al ${MY_ROOT}/my-flutter/engine
